### ISSUE TITLE
Would like to port it to arduino or stm32

### ISSUE THREAD

**Issue by maxtox** [Hell-Fire/WidebandO2#3]
Hi,
Thank you for your quick response to the last issue.

I have a good friend embedded developer to help to port the code...but need names of electronic parts you used...can you please support just a little?
I can give you my Skype ID or email if you like.
Thank you in advance!

**Comment by Hell-Fire** [comment]
I honestly can't remember what specific parts I used.  I no longer have the circuit to compare to.  U1 was some type of generic Quad OpAmp IC (rated for at least +5v, but was probably something higher), and T1 was any type of Darlington NPN transistor pair or N-FET, R2 is used as a pulldown if you use a FET, but a Darlington transistor wouldn't need it.

**Comment by pompushko** [comment]
@maxtox hello
I watn try port it to arduino
May be try do that together?

**Comment by maxtox** [comment]
Yes! Let's do it!

I already started :-) how to get in contact with you over Skype?

Am Mo., 29. Okt. 2018, 22:26 hat pompushko <notifications@github.com>
geschrieben:

**Comment by pompushko** [comment]
> Yes! Let's do it! I already started :-) how to get in contact with you over Skype? Am Mo., 29. Okt. 2018, 22:26 hat pompushko <notifications@github.com> geschrieben:

Sure, have it? Give me it i will try write you

**Comment by maxtox** [comment]
jewgenir_1

Am Mo., 29. Okt. 2018, 22:29 hat pompushko <notifications@github.com>
geschrieben:
