### ISSUE TITLE
Reference Pump Current

### ISSUE THREAD

**Issue by VITO1970** [Hell-Fire/WidebandO2#5]
Hello,
LSU4.2 needs reference gas(air) for correct work. In contrast of 4.2,   LSU4.9 has to be supplied with reference pump current ( = 20uA - according datasheet). How does your control unit provide reference pump current ?

**Comment by Hell-Fire** [comment]
From memory I think one of the outputs on the quad op-amp was supplying the reference pump current, but it has been a very long time since I had this circuit in operation, and even longer since I worked on it, so I could have overlooked that entirely.

**Comment by VITO1970** [comment]
Hello, Hell-Fire.
I see, this subject is not actual for you yet. However many thanks for your help!
I'm sure your experience will be usefull for me.
Best regards
Vito
